using Microsoft.EntityFrameworkCore;
using PROG7311POE.Models;
using System.Reflection.Emit;

namespace PROG7311POE.Data
{
    /// <summary>
    /// Stores data for employees to view farmer-products and farmers to sell products.
    /// </summary>
    public class MyDbContext : DbContext
    {
        public DbSet<User> Users { get; set; }
        public DbSet<Farmer> Farmers { get; set; }
        public DbSet<Product> Products { get; set; }

        /// <summary>
        /// Connect to local SQL-lite database on startup.
        /// </summary>
        /// <param name="options"></param>
        protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
            options.UseSqlite("Data Source=MyDatabase.db");
        }

        /// <summary>
        /// The tables priamry keys are autogenerated,
        /// </summary>
        /// <param name="modelBuilder"></param>
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>()
                .HasKey(u => u.UserID);

            modelBuilder.Entity<Farmer>()
                .HasKey(f => f.FarmerID);

            modelBuilder.Entity<Product>()
                .HasKey(p => p.ProductID);
        }

        /// <summary>
        /// For dependancy injection on startup.
        /// </summary>
        /// <param name="options"></param>
        public MyDbContext(DbContextOptions<MyDbContext> options) : base(options) { }
    }
}
